### ISSUE TITLE
Country map needs dropdown like city map for selecting timing

### ISSUE THREAD

**Issue by Matt-Vance** [projectunic0rn/travel-map-ui#98]
1) City Map needs to be able to switch "live" cities in database
2) Country Map needs to be able to switch "live" countries in database
3) After "live" country w/o city has been selected, "live" scorecard on City Map should read "0"
4) When clicking a "live" country, if it is the same country as before it should allow you to delete

**Comment by crfwilliams** [comment]
Can I work on this issue?
